# WireGuard client configuration example
# Generated by wireguard/server/configure.sh — do not edit manually.

[Interface]
PrivateKey = CLIENT_PRIVATE_KEY_HERE
Address = __WG_CLIENT_IP__/32
DNS = __WG_DNS__

[Peer]
PublicKey = SERVER_PUBLIC_KEY_HERE
# PresharedKey = PRESHARED_KEY_HERE   # optional
Endpoint = __SERVER_PUBLIC_IP__:__WG_PORT__
AllowedIPs = __WG_CLIENT_ALLOWED_IPS__
PersistentKeepalive = 25
